### PR TITLE
Include permission validation step to programmatically cloned repos

### LINKED ISSUE #2218: [ENH] - Programmatically added example repos cannot be deleted
### Feature description

If I try to delete a repo that was programmatically created via 
```
jupyterlab:
  initial_repositories:
    - <path/to/folder>: <github/repository/url>
```

I get a permission error: `rm: cannot remove 'examples/jatic-i3-demo': Permission denied`

### Value and/or benefit

This is an issue since the only way to get an updated example repo is to remove the repo folder. If I can't remove the folder, I can't pull an updated copy of the examples. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by viniciusdc**
## Reference Issues or PRs

fixes #2218 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by viniciusdc** [comment]
Before the new permission function check: (in this example, we are looking for the pre-initialized `examples/test` dir)

Captura de tela de 2024-02-16 14 31 50

After this PR changes: (triggered by removing `.firstrun`)
Captura de tela de 2024-02-16 14 33 48

Ps. I also tested removing the folder, all working (user had the `Developer` role to avoid all rights conflict given to `Admin`)

**Comment by viniciusdc** [comment]
The code "could" be heavily simplified for posteriority if we use `su -u 1000` or similar for the `mkdir` and `git clone` calls. Though this might cause permission errors with the rest of the container, so we would need to add some control to the container execution mode as well -- I vaguely remember that I had encountered a blocker while trying to do so with the init container specs, but this can be revisited later

File: src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/extras/git_clone_update.sh [hunk 1]
```diff
@@ -47,6 +63,9 @@ clone_update_repository() {
       mkdir -p "$folder_path"
     fi
 
+    # Fix parent directory permissions
```
Comment (viniciusdc) [inline src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/extras/git_clone_update.sh:66]:
```suggestion
```

**Review by marcelovilla — APPROVED** [review]
